/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cbccmemes;

import cbccmemes.mochila.Arma;
import cbccmemes.personagens.Aluno;
import java.awt.Frame;
import javax.swing.ComboBoxModel;

/**
 *
 * @author hundson
 */
public class CriaPersonagem extends javax.swing.JDialog {

    /**
     * Creates new form CriaPersonagem
     */
    public CriaPersonagem(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public CriaPersonagem(Frame parent, Aluno user, Arma armas[]){
        this(parent, true);
        this.user = user;
        this.armas = armas;
        this.setListArmas(SelectClasses.getItemAt(SelectClasses.getSelectedIndex()),armas);
    }
    
    private void setListArmas(String classe, Arma armas[]){
        String aux[] = Aluno.getArmasDisponiveis(classe, armas);
        SelectArmas.setModel(new javax.swing.DefaultComboBoxModel<>(aux));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ClasseLabel = new javax.swing.JLabel();
        SelectClasses = new javax.swing.JComboBox<>();
        NomeLabel1 = new javax.swing.JLabel();
        NomeLabel2 = new javax.swing.JLabel();
        hp_value = new javax.swing.JSpinner();
        NomeLabel3 = new javax.swing.JLabel();
        ataque_value = new javax.swing.JSpinner();
        NomeLabel4 = new javax.swing.JLabel();
        velocidade_value = new javax.swing.JSpinner();
        defesa_value = new javax.swing.JSpinner();
        ClasseLabel1 = new javax.swing.JLabel();
        SelectArmas = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criação de Personagem");

        NomeLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        NomeLabel.setText("Nome:");
        NomeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        ClasseLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        ClasseLabel.setText("Classe:");
        ClasseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        SelectClasses.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        SelectClasses.setModel(new javax.swing.DefaultComboBoxModel<>(Aluno.getClasses_personagem()));

        NomeLabel1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        NomeLabel1.setText("Ataque:");
        NomeLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        NomeLabel2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        NomeLabel2.setText("Velocidade:");
        NomeLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        hp_value.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        hp_value.setModel(new javax.swing.SpinnerNumberModel(1000, 1000, null, 1));
        hp_value.setEnabled(false);

        NomeLabel3.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        NomeLabel3.setText("HP:");
        NomeLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ataque_value.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        ataque_value.setModel(new javax.swing.SpinnerNumberModel(150, null, 450, 10));

        NomeLabel4.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        NomeLabel4.setText("Defesa:");
        NomeLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        velocidade_value.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        velocidade_value.setModel(new javax.swing.SpinnerNumberModel(150, null, 450, 10));

        defesa_value.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        defesa_value.setModel(new javax.swing.SpinnerNumberModel(150, null, 450, 10));

        ClasseLabel1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        ClasseLabel1.setText("Arma:");
        ClasseLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        SelectArmas.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SelectClasses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(hp_value, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NomeLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NomeLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ataque_value)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeLabel2)
                            .addComponent(NomeLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(defesa_value)
                            .addComponent(velocidade_value, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(SelectArmas, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeLabel)
                            .addComponent(ClasseLabel)
                            .addComponent(ClasseLabel1)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ClasseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel3)
                    .addComponent(hp_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeLabel2)
                    .addComponent(velocidade_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ataque_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeLabel4)
                    .addComponent(defesa_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ClasseLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectArmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //System.err.println("Teste:"+armas[0].getNome()+armas[0].getClasse_associada());
        System.err.println("Teste:"+Aluno.getArmasDisponiveis(SelectClasses.getItemAt(SelectClasses.getSelectedIndex()), armas));
        this.setListArmas(SelectClasses.getItemAt(SelectClasses.getSelectedIndex()), armas);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriaPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriaPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriaPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriaPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CriaPersonagem dialog = new CriaPersonagem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClasseLabel;
    private javax.swing.JLabel ClasseLabel1;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JLabel NomeLabel1;
    private javax.swing.JLabel NomeLabel2;
    private javax.swing.JLabel NomeLabel3;
    private javax.swing.JLabel NomeLabel4;
    private javax.swing.JComboBox<String> SelectArmas;
    private javax.swing.JComboBox<String> SelectClasses;
    private javax.swing.JSpinner ataque_value;
    private javax.swing.JSpinner defesa_value;
    private javax.swing.JSpinner hp_value;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSpinner velocidade_value;
    // End of variables declaration//GEN-END:variables
    private Aluno user;
    private Arma armas[];
}
