/*
 * To change this licen            @Override
            public int getSize() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public Object getElementAt(int index) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void addListDataListener(ListDataListener l) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void removeListDataListener(ListDataListener l) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }e header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cbccmemes;

import cbccmemes.personagens.Aluno;
import cbccmemes.personagens.Personagem;
import javax.swing.ImageIcon;

/**
 *
 * @author 201604940039
 */
public class DescricaoPersonagem extends javax.swing.JDialog {

    /**
     * Creates new form DescricaoPersonagem
     */
    public DescricaoPersonagem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void setDados(Personagem person){
        setDados(person, true);
    }
    
    public void setDados(Personagem person, boolean mochila){
        NomeField.setText(person.getNome());
        NivelField.setText(""+person.getNivel());
        if ( person.getClass() == Aluno.class && mochila){
            Aluno aluno = (Aluno) person;
            crg_value.setName("CRG:");
            ClasseField.setText(aluno.getClasse_aluno());
            ExpField.setValue(aluno.getBarra_experiencia());
            
            //Carrega lista de Armas na mochila
            ArmaList.setModel(new javax.swing.AbstractListModel<String>(){
                String[] strings = aluno.getNomesArmas();
                public int getSize(){ return strings.length; }
                public String getElementAt(int i) { return strings[i]; }
            });
            //Carrega lista de Itens na mochila
            ItemList.setModel(new javax.swing.AbstractListModel<String>() {
                String[] strings = aluno.getNomesItens();
                public int getSize(){ return strings.length; }
                public String getElementAt(int i){ return strings[i]; }
            });
            
        }else{
            Mochila.setVisible(false);
            this.setSize(this.getWidth(), 420);
            ExpLabel.setVisible(false);
            ExpField.setVisible(false);
        }        
        if ( person.getArma_equipada() != null )
            ArmaField.setText(person.getArma_equipada().getNome());
        else
            ArmaField.setText("Nenhuma");
        
        if ( person.getItem_equipado() != null )
            ItemField.setText(person.getItem_equipado().getNome());
        else
            ItemField.setText("Nenhum");
        
        crg_value.setValue(person.getVida());
        ataque_value.setValue(person.getAtaque());
        defesa_value.setValue(person.getDefesa());
        velocidade_value.setValue(person.getVelocidade());
        
        try {
            AvatarPersonagem.setIcon(new ImageIcon(getClass().getResource(person.getUrl_imagem())));
        } catch (Exception e) {
            AvatarPersonagem.setIcon(new ImageIcon(getClass().getResource("imagens/avatar.png")));
        }
        //if (getClass().getResource(person.getUrl_imagem()) != null)
            //AvatarPersonagem.setIcon(new ImageIcon(getClass().getResource(person.getUrl_imagem())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AvatarPersonagem = new javax.swing.JLabel();
        Dados = new javax.swing.JPanel();
        NomeLabel = new javax.swing.JLabel();
        NivelLabel = new javax.swing.JLabel();
        ClasseLabel = new javax.swing.JLabel();
        ArmaLabel = new javax.swing.JLabel();
        ItemLabel = new javax.swing.JLabel();
        NivelField = new javax.swing.JLabel();
        ArmaField = new javax.swing.JLabel();
        ClasseField = new javax.swing.JLabel();
        NomeField = new javax.swing.JLabel();
        ItemField = new javax.swing.JLabel();
        ExpLabel = new javax.swing.JLabel();
        ExpField = new javax.swing.JProgressBar();
        Mochila = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ItemList = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ArmaList = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Stats = new javax.swing.JPanel();
        defesa_value = new javax.swing.JSpinner();
        NomeLabel1 = new javax.swing.JLabel();
        NomeLabel2 = new javax.swing.JLabel();
        crg_value = new javax.swing.JSpinner();
        NomeLabel3 = new javax.swing.JLabel();
        ataque_value = new javax.swing.JSpinner();
        NomeLabel4 = new javax.swing.JLabel();
        velocidade_value = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Descrição do Personagem");
        setResizable(false);

        AvatarPersonagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AvatarPersonagem.setBorder(javax.swing.BorderFactory.createTitledBorder("Avatar"));

        Dados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        Dados.setMinimumSize(new java.awt.Dimension(223, 217));

        NomeLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        NomeLabel.setText("Nome:");
        NomeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        NivelLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        NivelLabel.setText("Nível:");
        NivelLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ClasseLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        ClasseLabel.setText("Classe:");
        ClasseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ArmaLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        ArmaLabel.setText("Arma:");
        ArmaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ItemLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        ItemLabel.setText("Item:");
        ItemLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        NivelField.setText("Nível Personagem");

        ArmaField.setText("Arma Personagem");

        ClasseField.setText("Classe Personagem");

        NomeField.setText("Nome Personagem");

        ItemField.setText("Item Personagem");

        ExpLabel.setText("Experiência:");

        javax.swing.GroupLayout DadosLayout = new javax.swing.GroupLayout(Dados);
        Dados.setLayout(DadosLayout);
        DadosLayout.setHorizontalGroup(
            DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ExpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ClasseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NomeLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NivelLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ArmaLabel, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(NivelField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClasseField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ArmaField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ItemField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExpField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NomeField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        DadosLayout.setVerticalGroup(
            DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel)
                    .addComponent(NomeField))
                .addGap(18, 18, 18)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NivelLabel)
                    .addComponent(NivelField))
                .addGap(18, 18, 18)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClasseLabel)
                    .addComponent(ClasseField))
                .addGap(18, 18, 18)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArmaLabel)
                    .addComponent(ArmaField))
                .addGap(18, 18, 18)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemLabel)
                    .addComponent(ItemField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExpLabel)
                    .addComponent(ExpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Mochila.setBorder(javax.swing.BorderFactory.createTitledBorder("Mochila"));

        ItemList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ItemList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Itens", jPanel3);

        ArmaList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Arma 1", "Arma 2", "Arma 3", "Arma 4", "Arma 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ArmaList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Armas", jPanel4);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout MochilaLayout = new javax.swing.GroupLayout(Mochila);
        Mochila.setLayout(MochilaLayout);
        MochilaLayout.setHorizontalGroup(
            MochilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MochilaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MochilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        MochilaLayout.setVerticalGroup(
            MochilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MochilaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MochilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MochilaLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Stats.setBorder(javax.swing.BorderFactory.createTitledBorder("Stats"));

        defesa_value.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        defesa_value.setEnabled(false);

        NomeLabel1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        NomeLabel1.setText("Ataque:");
        NomeLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        NomeLabel2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        NomeLabel2.setText("Velocidade:");
        NomeLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        crg_value.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        crg_value.setEnabled(false);

        NomeLabel3.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        NomeLabel3.setText("Vida:");
        NomeLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ataque_value.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        ataque_value.setEnabled(false);

        NomeLabel4.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        NomeLabel4.setText("Defesa:");
        NomeLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        velocidade_value.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        velocidade_value.setEnabled(false);

        javax.swing.GroupLayout StatsLayout = new javax.swing.GroupLayout(Stats);
        Stats.setLayout(StatsLayout);
        StatsLayout.setHorizontalGroup(
            StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StatsLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(crg_value))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StatsLayout.createSequentialGroup()
                        .addComponent(NomeLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StatsLayout.createSequentialGroup()
                        .addComponent(NomeLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ataque_value)))
                .addGap(96, 96, 96)
                .addGroup(StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatsLayout.createSequentialGroup()
                        .addComponent(NomeLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(defesa_value))
                    .addGroup(StatsLayout.createSequentialGroup()
                        .addComponent(NomeLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(velocidade_value)))
                .addContainerGap())
        );
        StatsLayout.setVerticalGroup(
            StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel3)
                    .addComponent(crg_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeLabel4)
                    .addComponent(defesa_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NomeLabel2)
                        .addComponent(velocidade_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NomeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ataque_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Stats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Mochila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Dados, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AvatarPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AvatarPersonagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Stats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Mochila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DescricaoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DescricaoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DescricaoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DescricaoPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DescricaoPersonagem dialog = new DescricaoPersonagem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArmaField;
    private javax.swing.JLabel ArmaLabel;
    private javax.swing.JList<String> ArmaList;
    private javax.swing.JLabel AvatarPersonagem;
    private javax.swing.JLabel ClasseField;
    private javax.swing.JLabel ClasseLabel;
    private javax.swing.JPanel Dados;
    private javax.swing.JProgressBar ExpField;
    private javax.swing.JLabel ExpLabel;
    private javax.swing.JLabel ItemField;
    private javax.swing.JLabel ItemLabel;
    private javax.swing.JList<String> ItemList;
    private javax.swing.JPanel Mochila;
    private javax.swing.JLabel NivelField;
    private javax.swing.JLabel NivelLabel;
    private javax.swing.JLabel NomeField;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JLabel NomeLabel1;
    private javax.swing.JLabel NomeLabel2;
    private javax.swing.JLabel NomeLabel3;
    private javax.swing.JLabel NomeLabel4;
    private javax.swing.JPanel Stats;
    private javax.swing.JSpinner ataque_value;
    private javax.swing.JSpinner crg_value;
    private javax.swing.JSpinner defesa_value;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner velocidade_value;
    // End of variables declaration//GEN-END:variables
}
